import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;

public class Cliente extends javax.swing.JFrame {
    private static final String HOST = "localhost";
    private static final int PUERTO = 5000;
    private Socket sc;
    private DataInputStream entrada;
    private DataOutputStream salida;
    private int ficha = 0;
    private String mensajeEnviar = "";
    
    public Cliente() {
        initComponents();
        setLocationRelativeTo(null);
        inicializarCliente();
    }
    
    public void inicializarCliente() {
        try {
            sc = new Socket(HOST, PUERTO);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al tratar de conectarse con el hotel");
        }
    }
    
    public void limpiar() {
        nameField.setText("");
        idField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getFichaBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getFichaBtn.setText("Obtener ficha");
        getFichaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFichaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(getFichaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, 130));

        nameField.setText("nombre");
        nameField.setToolTipText("Ingrese su nombre completo");
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 160, -1));

        idField.setText("identificacion");
        idField.setToolTipText("Ingrese su identificacion");
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getFichaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFichaBtnActionPerformed
           try {
                entrada = new DataInputStream(sc.getInputStream());
                salida = new DataOutputStream(sc.getOutputStream());
           
//                mensajeEnviar = nameField.getText();
//                salida.writeUTF(mensajeEnviar);
//                mensajeEnviar = idField.getText();
//                salida.writeLong(Long.parseLong(mensajeEnviar));
                // se envian los datos
                // luego obtenemos la ficha de entrada
                ficha = entrada.readInt();
           JOptionPane.showMessageDialog(null, "Ficha no: " + ficha);
           } catch (IOException ex) {
               
           }


    }//GEN-LAST:event_getFichaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton getFichaBtn;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
